Check that required config file command line arguments are present
grok-fsck and grok-pull require specifying the path to a config file on
the command line. Generate an error message if the argument is not
present rather than a traceback:

edmonds@chase{0}:~$ grok-pull
Traceback (most recent call last):
  File "/usr/bin/grok-pull", line 630, in <module>
    ini.read(opts.config)
  File "/usr/lib/python2.7/ConfigParser.py", line 300, in read
    for filename in filenames:
TypeError: 'NoneType' object is not iterable
edmonds@chase{1}:~$

Signed-off-by: Robert S. Edmonds <edmonds@debian.org>
Signed-off-by: Konstantin Ryabitsev <mricon@kernel.org>